/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UspsAlert {
        /**
          * @default false
         */
        "dismissible": boolean;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default 'info'
         */
        "variant": 'info' | 'success' | 'warning' | 'error';
    }
    interface UspsBadge {
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'info'
         */
        "variant": 'info' | 'success' | 'warning' | 'error';
    }
    interface UspsButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'ecommerce' | 'inactive';
    }
    interface UspsCard {
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default 'large'
         */
        "variant": 'large' | 'small' | 'image';
    }
    interface UspsCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UspsContainer {
        /**
          * @default 'lg'
         */
        "size": 'sm' | 'md' | 'lg' | 'full';
    }
    interface UspsDivider {
        /**
          * @default ''
         */
        "color": string;
        /**
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
    }
    interface UspsFormField {
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default ''
         */
        "hint": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "required": boolean;
    }
    interface UspsGrid {
        /**
          * @default 'stretch'
         */
        "align": 'start' | 'center' | 'end' | 'stretch';
        /**
          * @default 12
         */
        "columns": number | string;
        /**
          * @default '16px'
         */
        "gap": string;
    }
    interface UspsIcon {
        /**
          * @default 'default'
         */
        "color": 'default' | 'success' | 'failure' | 'warning' | 'gray';
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default 'sm'
         */
        "size": 'xsm' | 'sm' | 'md' | 'lg' | 'xlg';
    }
    interface UspsInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UspsLink {
        /**
          * @default false
         */
        "external": boolean;
        /**
          * @default '#'
         */
        "href": string;
        /**
          * @default 'body'
         */
        "variant": 'body' | 'heading' | 'ecommerce';
    }
    interface UspsModal {
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default '800px'
         */
        "width": string;
    }
    interface UspsRadio {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UspsSelect {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default '[]'
         */
        "options": string | Array<{ label: string; value: string }>;
        /**
          * @default 'Select an option'
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UspsSpinner {
        /**
          * @default 'primary'
         */
        "color": 'primary' | 'white';
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
    interface UspsStack {
        /**
          * @default 'stretch'
         */
        "align": 'start' | 'center' | 'end' | 'stretch';
        /**
          * @default 'column'
         */
        "direction": 'row' | 'column';
        /**
          * @default '16px'
         */
        "gap": string;
    }
    interface UspsTextarea {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 4
         */
        "rows": number;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UspsTheme {
        /**
          * @default 'light'
         */
        "theme": 'light' | 'dark';
    }
    interface UspsToast {
        /**
          * @default 5000
         */
        "duration": number;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'top-right'
         */
        "position": 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
        /**
          * @default 'info'
         */
        "variant": 'info' | 'success' | 'warning' | 'error';
    }
    interface UspsToggle {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
    }
    interface UspsTooltip {
        /**
          * @default ''
         */
        "content": string;
        /**
          * @default 'top'
         */
        "position": 'top' | 'bottom' | 'left' | 'right';
    }
}
export interface UspsAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUspsAlertElement;
}
export interface UspsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUspsButtonElement;
}
export interface UspsCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUspsCheckboxElement;
}
export interface UspsInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUspsInputElement;
}
export interface UspsModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUspsModalElement;
}
export interface UspsRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUspsRadioElement;
}
export interface UspsSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUspsSelectElement;
}
export interface UspsTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUspsTextareaElement;
}
export interface UspsToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUspsToastElement;
}
export interface UspsToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUspsToggleElement;
}
declare global {
    interface HTMLUspsAlertElementEventMap {
        "uspsDismiss": void;
    }
    interface HTMLUspsAlertElement extends Components.UspsAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUspsAlertElementEventMap>(type: K, listener: (this: HTMLUspsAlertElement, ev: UspsAlertCustomEvent<HTMLUspsAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUspsAlertElementEventMap>(type: K, listener: (this: HTMLUspsAlertElement, ev: UspsAlertCustomEvent<HTMLUspsAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUspsAlertElement: {
        prototype: HTMLUspsAlertElement;
        new (): HTMLUspsAlertElement;
    };
    interface HTMLUspsBadgeElement extends Components.UspsBadge, HTMLStencilElement {
    }
    var HTMLUspsBadgeElement: {
        prototype: HTMLUspsBadgeElement;
        new (): HTMLUspsBadgeElement;
    };
    interface HTMLUspsButtonElementEventMap {
        "uspsClick": void;
    }
    interface HTMLUspsButtonElement extends Components.UspsButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUspsButtonElementEventMap>(type: K, listener: (this: HTMLUspsButtonElement, ev: UspsButtonCustomEvent<HTMLUspsButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUspsButtonElementEventMap>(type: K, listener: (this: HTMLUspsButtonElement, ev: UspsButtonCustomEvent<HTMLUspsButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUspsButtonElement: {
        prototype: HTMLUspsButtonElement;
        new (): HTMLUspsButtonElement;
    };
    interface HTMLUspsCardElement extends Components.UspsCard, HTMLStencilElement {
    }
    var HTMLUspsCardElement: {
        prototype: HTMLUspsCardElement;
        new (): HTMLUspsCardElement;
    };
    interface HTMLUspsCheckboxElementEventMap {
        "uspsChange": boolean;
    }
    interface HTMLUspsCheckboxElement extends Components.UspsCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUspsCheckboxElementEventMap>(type: K, listener: (this: HTMLUspsCheckboxElement, ev: UspsCheckboxCustomEvent<HTMLUspsCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUspsCheckboxElementEventMap>(type: K, listener: (this: HTMLUspsCheckboxElement, ev: UspsCheckboxCustomEvent<HTMLUspsCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUspsCheckboxElement: {
        prototype: HTMLUspsCheckboxElement;
        new (): HTMLUspsCheckboxElement;
    };
    interface HTMLUspsContainerElement extends Components.UspsContainer, HTMLStencilElement {
    }
    var HTMLUspsContainerElement: {
        prototype: HTMLUspsContainerElement;
        new (): HTMLUspsContainerElement;
    };
    interface HTMLUspsDividerElement extends Components.UspsDivider, HTMLStencilElement {
    }
    var HTMLUspsDividerElement: {
        prototype: HTMLUspsDividerElement;
        new (): HTMLUspsDividerElement;
    };
    interface HTMLUspsFormFieldElement extends Components.UspsFormField, HTMLStencilElement {
    }
    var HTMLUspsFormFieldElement: {
        prototype: HTMLUspsFormFieldElement;
        new (): HTMLUspsFormFieldElement;
    };
    interface HTMLUspsGridElement extends Components.UspsGrid, HTMLStencilElement {
    }
    var HTMLUspsGridElement: {
        prototype: HTMLUspsGridElement;
        new (): HTMLUspsGridElement;
    };
    interface HTMLUspsIconElement extends Components.UspsIcon, HTMLStencilElement {
    }
    var HTMLUspsIconElement: {
        prototype: HTMLUspsIconElement;
        new (): HTMLUspsIconElement;
    };
    interface HTMLUspsInputElementEventMap {
        "uspsInput": string;
        "uspsChange": string;
    }
    interface HTMLUspsInputElement extends Components.UspsInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUspsInputElementEventMap>(type: K, listener: (this: HTMLUspsInputElement, ev: UspsInputCustomEvent<HTMLUspsInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUspsInputElementEventMap>(type: K, listener: (this: HTMLUspsInputElement, ev: UspsInputCustomEvent<HTMLUspsInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUspsInputElement: {
        prototype: HTMLUspsInputElement;
        new (): HTMLUspsInputElement;
    };
    interface HTMLUspsLinkElement extends Components.UspsLink, HTMLStencilElement {
    }
    var HTMLUspsLinkElement: {
        prototype: HTMLUspsLinkElement;
        new (): HTMLUspsLinkElement;
    };
    interface HTMLUspsModalElementEventMap {
        "uspsClose": void;
    }
    interface HTMLUspsModalElement extends Components.UspsModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUspsModalElementEventMap>(type: K, listener: (this: HTMLUspsModalElement, ev: UspsModalCustomEvent<HTMLUspsModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUspsModalElementEventMap>(type: K, listener: (this: HTMLUspsModalElement, ev: UspsModalCustomEvent<HTMLUspsModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUspsModalElement: {
        prototype: HTMLUspsModalElement;
        new (): HTMLUspsModalElement;
    };
    interface HTMLUspsRadioElementEventMap {
        "uspsChange": string;
    }
    interface HTMLUspsRadioElement extends Components.UspsRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUspsRadioElementEventMap>(type: K, listener: (this: HTMLUspsRadioElement, ev: UspsRadioCustomEvent<HTMLUspsRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUspsRadioElementEventMap>(type: K, listener: (this: HTMLUspsRadioElement, ev: UspsRadioCustomEvent<HTMLUspsRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUspsRadioElement: {
        prototype: HTMLUspsRadioElement;
        new (): HTMLUspsRadioElement;
    };
    interface HTMLUspsSelectElementEventMap {
        "uspsChange": string;
    }
    interface HTMLUspsSelectElement extends Components.UspsSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUspsSelectElementEventMap>(type: K, listener: (this: HTMLUspsSelectElement, ev: UspsSelectCustomEvent<HTMLUspsSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUspsSelectElementEventMap>(type: K, listener: (this: HTMLUspsSelectElement, ev: UspsSelectCustomEvent<HTMLUspsSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUspsSelectElement: {
        prototype: HTMLUspsSelectElement;
        new (): HTMLUspsSelectElement;
    };
    interface HTMLUspsSpinnerElement extends Components.UspsSpinner, HTMLStencilElement {
    }
    var HTMLUspsSpinnerElement: {
        prototype: HTMLUspsSpinnerElement;
        new (): HTMLUspsSpinnerElement;
    };
    interface HTMLUspsStackElement extends Components.UspsStack, HTMLStencilElement {
    }
    var HTMLUspsStackElement: {
        prototype: HTMLUspsStackElement;
        new (): HTMLUspsStackElement;
    };
    interface HTMLUspsTextareaElementEventMap {
        "uspsInput": string;
        "uspsChange": string;
    }
    interface HTMLUspsTextareaElement extends Components.UspsTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUspsTextareaElementEventMap>(type: K, listener: (this: HTMLUspsTextareaElement, ev: UspsTextareaCustomEvent<HTMLUspsTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUspsTextareaElementEventMap>(type: K, listener: (this: HTMLUspsTextareaElement, ev: UspsTextareaCustomEvent<HTMLUspsTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUspsTextareaElement: {
        prototype: HTMLUspsTextareaElement;
        new (): HTMLUspsTextareaElement;
    };
    interface HTMLUspsThemeElement extends Components.UspsTheme, HTMLStencilElement {
    }
    var HTMLUspsThemeElement: {
        prototype: HTMLUspsThemeElement;
        new (): HTMLUspsThemeElement;
    };
    interface HTMLUspsToastElementEventMap {
        "uspsDismiss": void;
    }
    interface HTMLUspsToastElement extends Components.UspsToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUspsToastElementEventMap>(type: K, listener: (this: HTMLUspsToastElement, ev: UspsToastCustomEvent<HTMLUspsToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUspsToastElementEventMap>(type: K, listener: (this: HTMLUspsToastElement, ev: UspsToastCustomEvent<HTMLUspsToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUspsToastElement: {
        prototype: HTMLUspsToastElement;
        new (): HTMLUspsToastElement;
    };
    interface HTMLUspsToggleElementEventMap {
        "uspsChange": boolean;
    }
    interface HTMLUspsToggleElement extends Components.UspsToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUspsToggleElementEventMap>(type: K, listener: (this: HTMLUspsToggleElement, ev: UspsToggleCustomEvent<HTMLUspsToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUspsToggleElementEventMap>(type: K, listener: (this: HTMLUspsToggleElement, ev: UspsToggleCustomEvent<HTMLUspsToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUspsToggleElement: {
        prototype: HTMLUspsToggleElement;
        new (): HTMLUspsToggleElement;
    };
    interface HTMLUspsTooltipElement extends Components.UspsTooltip, HTMLStencilElement {
    }
    var HTMLUspsTooltipElement: {
        prototype: HTMLUspsTooltipElement;
        new (): HTMLUspsTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "usps-alert": HTMLUspsAlertElement;
        "usps-badge": HTMLUspsBadgeElement;
        "usps-button": HTMLUspsButtonElement;
        "usps-card": HTMLUspsCardElement;
        "usps-checkbox": HTMLUspsCheckboxElement;
        "usps-container": HTMLUspsContainerElement;
        "usps-divider": HTMLUspsDividerElement;
        "usps-form-field": HTMLUspsFormFieldElement;
        "usps-grid": HTMLUspsGridElement;
        "usps-icon": HTMLUspsIconElement;
        "usps-input": HTMLUspsInputElement;
        "usps-link": HTMLUspsLinkElement;
        "usps-modal": HTMLUspsModalElement;
        "usps-radio": HTMLUspsRadioElement;
        "usps-select": HTMLUspsSelectElement;
        "usps-spinner": HTMLUspsSpinnerElement;
        "usps-stack": HTMLUspsStackElement;
        "usps-textarea": HTMLUspsTextareaElement;
        "usps-theme": HTMLUspsThemeElement;
        "usps-toast": HTMLUspsToastElement;
        "usps-toggle": HTMLUspsToggleElement;
        "usps-tooltip": HTMLUspsTooltipElement;
    }
}
declare namespace LocalJSX {
    interface UspsAlert {
        /**
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * @default ''
         */
        "heading"?: string;
        "onUspsDismiss"?: (event: UspsAlertCustomEvent<void>) => void;
        /**
          * @default 'info'
         */
        "variant"?: 'info' | 'success' | 'warning' | 'error';
    }
    interface UspsBadge {
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'info'
         */
        "variant"?: 'info' | 'success' | 'warning' | 'error';
    }
    interface UspsButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onUspsClick"?: (event: UspsButtonCustomEvent<void>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'ecommerce' | 'inactive';
    }
    interface UspsCard {
        /**
          * @default ''
         */
        "heading"?: string;
        /**
          * @default 'large'
         */
        "variant"?: 'large' | 'small' | 'image';
    }
    interface UspsCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onUspsChange"?: (event: UspsCheckboxCustomEvent<boolean>) => void;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UspsContainer {
        /**
          * @default 'lg'
         */
        "size"?: 'sm' | 'md' | 'lg' | 'full';
    }
    interface UspsDivider {
        /**
          * @default ''
         */
        "color"?: string;
        /**
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
    }
    interface UspsFormField {
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "hint"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
    }
    interface UspsGrid {
        /**
          * @default 'stretch'
         */
        "align"?: 'start' | 'center' | 'end' | 'stretch';
        /**
          * @default 12
         */
        "columns"?: number | string;
        /**
          * @default '16px'
         */
        "gap"?: string;
    }
    interface UspsIcon {
        /**
          * @default 'default'
         */
        "color"?: 'default' | 'success' | 'failure' | 'warning' | 'gray';
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        /**
          * @default 'sm'
         */
        "size"?: 'xsm' | 'sm' | 'md' | 'lg' | 'xlg';
    }
    interface UspsInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onUspsChange"?: (event: UspsInputCustomEvent<string>) => void;
        "onUspsInput"?: (event: UspsInputCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UspsLink {
        /**
          * @default false
         */
        "external"?: boolean;
        /**
          * @default '#'
         */
        "href"?: string;
        /**
          * @default 'body'
         */
        "variant"?: 'body' | 'heading' | 'ecommerce';
    }
    interface UspsModal {
        /**
          * @default ''
         */
        "heading"?: string;
        "onUspsClose"?: (event: UspsModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default '800px'
         */
        "width"?: string;
    }
    interface UspsRadio {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onUspsChange"?: (event: UspsRadioCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UspsSelect {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onUspsChange"?: (event: UspsSelectCustomEvent<string>) => void;
        /**
          * @default '[]'
         */
        "options"?: string | Array<{ label: string; value: string }>;
        /**
          * @default 'Select an option'
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UspsSpinner {
        /**
          * @default 'primary'
         */
        "color"?: 'primary' | 'white';
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface UspsStack {
        /**
          * @default 'stretch'
         */
        "align"?: 'start' | 'center' | 'end' | 'stretch';
        /**
          * @default 'column'
         */
        "direction"?: 'row' | 'column';
        /**
          * @default '16px'
         */
        "gap"?: string;
    }
    interface UspsTextarea {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onUspsChange"?: (event: UspsTextareaCustomEvent<string>) => void;
        "onUspsInput"?: (event: UspsTextareaCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 4
         */
        "rows"?: number;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UspsTheme {
        /**
          * @default 'light'
         */
        "theme"?: 'light' | 'dark';
    }
    interface UspsToast {
        /**
          * @default 5000
         */
        "duration"?: number;
        "onUspsDismiss"?: (event: UspsToastCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'top-right'
         */
        "position"?: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
        /**
          * @default 'info'
         */
        "variant"?: 'info' | 'success' | 'warning' | 'error';
    }
    interface UspsToggle {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onUspsChange"?: (event: UspsToggleCustomEvent<boolean>) => void;
    }
    interface UspsTooltip {
        /**
          * @default ''
         */
        "content"?: string;
        /**
          * @default 'top'
         */
        "position"?: 'top' | 'bottom' | 'left' | 'right';
    }
    interface IntrinsicElements {
        "usps-alert": UspsAlert;
        "usps-badge": UspsBadge;
        "usps-button": UspsButton;
        "usps-card": UspsCard;
        "usps-checkbox": UspsCheckbox;
        "usps-container": UspsContainer;
        "usps-divider": UspsDivider;
        "usps-form-field": UspsFormField;
        "usps-grid": UspsGrid;
        "usps-icon": UspsIcon;
        "usps-input": UspsInput;
        "usps-link": UspsLink;
        "usps-modal": UspsModal;
        "usps-radio": UspsRadio;
        "usps-select": UspsSelect;
        "usps-spinner": UspsSpinner;
        "usps-stack": UspsStack;
        "usps-textarea": UspsTextarea;
        "usps-theme": UspsTheme;
        "usps-toast": UspsToast;
        "usps-toggle": UspsToggle;
        "usps-tooltip": UspsTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "usps-alert": LocalJSX.UspsAlert & JSXBase.HTMLAttributes<HTMLUspsAlertElement>;
            "usps-badge": LocalJSX.UspsBadge & JSXBase.HTMLAttributes<HTMLUspsBadgeElement>;
            "usps-button": LocalJSX.UspsButton & JSXBase.HTMLAttributes<HTMLUspsButtonElement>;
            "usps-card": LocalJSX.UspsCard & JSXBase.HTMLAttributes<HTMLUspsCardElement>;
            "usps-checkbox": LocalJSX.UspsCheckbox & JSXBase.HTMLAttributes<HTMLUspsCheckboxElement>;
            "usps-container": LocalJSX.UspsContainer & JSXBase.HTMLAttributes<HTMLUspsContainerElement>;
            "usps-divider": LocalJSX.UspsDivider & JSXBase.HTMLAttributes<HTMLUspsDividerElement>;
            "usps-form-field": LocalJSX.UspsFormField & JSXBase.HTMLAttributes<HTMLUspsFormFieldElement>;
            "usps-grid": LocalJSX.UspsGrid & JSXBase.HTMLAttributes<HTMLUspsGridElement>;
            "usps-icon": LocalJSX.UspsIcon & JSXBase.HTMLAttributes<HTMLUspsIconElement>;
            "usps-input": LocalJSX.UspsInput & JSXBase.HTMLAttributes<HTMLUspsInputElement>;
            "usps-link": LocalJSX.UspsLink & JSXBase.HTMLAttributes<HTMLUspsLinkElement>;
            "usps-modal": LocalJSX.UspsModal & JSXBase.HTMLAttributes<HTMLUspsModalElement>;
            "usps-radio": LocalJSX.UspsRadio & JSXBase.HTMLAttributes<HTMLUspsRadioElement>;
            "usps-select": LocalJSX.UspsSelect & JSXBase.HTMLAttributes<HTMLUspsSelectElement>;
            "usps-spinner": LocalJSX.UspsSpinner & JSXBase.HTMLAttributes<HTMLUspsSpinnerElement>;
            "usps-stack": LocalJSX.UspsStack & JSXBase.HTMLAttributes<HTMLUspsStackElement>;
            "usps-textarea": LocalJSX.UspsTextarea & JSXBase.HTMLAttributes<HTMLUspsTextareaElement>;
            "usps-theme": LocalJSX.UspsTheme & JSXBase.HTMLAttributes<HTMLUspsThemeElement>;
            "usps-toast": LocalJSX.UspsToast & JSXBase.HTMLAttributes<HTMLUspsToastElement>;
            "usps-toggle": LocalJSX.UspsToggle & JSXBase.HTMLAttributes<HTMLUspsToggleElement>;
            "usps-tooltip": LocalJSX.UspsTooltip & JSXBase.HTMLAttributes<HTMLUspsTooltipElement>;
        }
    }
}
